name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://free.v36.cm/v1
          MODEL: gpt-3.5-turbo
          LANGUAGE: English
          MAX_PATCH_LENGTH: 10000
          PROMPT: Please review the code and check for potential issues including memory management, thread safety, error handling, and code organization. 